name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get more space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30720
          swap-size-mb: 4096
          remove-dotnet: "true"
          remove-android: "true"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: armbian/build
          ref: main
          path: build
      - name: Build
        shell: bash
        run: |
          cd ./build
          ./compile.sh \
            BOARD=rock-5a \
            BRANCH=current \
            RELEASE=bookworm \
            BUILD_MINIMAL=no \
            KERNEL_CONFIGURE=no \
            EXPERT=yes \
            COMPRESS_OUTPUTIMAGE=sha,gpg,xz \
            INSTALL_HEADERS=yes \
            INSTALL_ARM_CONFIG=yes \
            BUILD_DESKTOP=no
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/output/images/*
          overwrite: true
          file_glob: true
